sensor:
  - platform: austria_public_transport
    name: "Wiener Linien"
    stops:
      - '1442'
      - '1480'
      - '3529'
      - '664'
      - '4923'
      - '4918'
      - '4620'
      - '4609'
